version: "3.8"
services:
  prestashop:
    image: prestashop/prestashop:latest
    container_name: prestashop
    volumes:
      - ${HOME}/NetBeansProjects/PHP/prestashop:/var/www/html
    environment:
      - PS_DEV_MODE=false
      - PS_INSTALL_AUTO=0
      - DB_SERVER=prestashop-mysql
    ports:
      - "8080:80"
    depends_on:
      - prestashop-mysql
    networks:
      - local-net

  prestashop-mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
     - "3307:3306"
    environment:
     - MYSQL_ROOT_PASSWORD=kabamysql
    networks:
      - local-net
    volumes:
      - ${HOME}/storage/docker/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
     - "8081:80"
    volumes:
     - /sessions
    environment:
     - PMA_HOST=prestashop-mysql
    networks:
     - local-net
  
  mariadb:
    image: mariadb:10.5.3
    container_name: mariadb
    volumes:
      - ~/storage/docker/mariadb/:/var/lib/mysql/
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=kabamysql
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
      - MYSQL_DATABASE=registre_naissances
    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
    networks:
      - local-net
   
  mongo:
    image: mongo:4.2.6
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - ~/storage/docker/mongo:/data/db
    restart: always
    
networks:
    local-net:
