version: "3.8"
services:
  mongo:
    image: mongo:4.4.2
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - ~/storage/docker/mongo:/data/db
    restart: always
    networks:
      - mongo-net

networks:
  mongo-net:
