databases-up:
	docker-compose -f docker-compose-databases.yml up -d --remove-orphans

databases-down:
	docker-compose -f docker-compose-databases.yml down

databases-logs:
	docker-compose -f docker-compose-databases.yml logs -f

databases-ps:
	docker-compose -f docker-compose-databases.yml ps

mongo-up:
	docker-compose -f docker-compose-mongo.yml up -d --remove-orphans

mongo-down:
	docker-compose -f docker-compose-mongo.yml down

mongo-logs:
	docker-compose -f docker-compose-mongo.yml logs -f

mongo-ps:
	docker-compose -f docker-compose-mongo.yml ps

prestashop-up:
	docker-compose -f prestashop.yml up -d --remove-orphans

prestashop-down:
	docker-compose -f prestashop.yml down

prestashop-logs:
	docker-compose -f prestashop.yml logs -f

prestashop-ps:
	docker-compose -f prestashop.yml ps