version: "3.8"
services:
  prestashop:
    image: prestashop/prestashop:latest
    container_name: prestashop
    restart: always
    volumes:
      - /var/www/html/prestashop:/var/www/html
    environment:
      - PS_DEV_MODE=false
      - PS_INSTALL_AUTO=0
      - DB_SERVER=mysql
    ports:
      - "8282:80"
    depends_on:
      - mysql
    networks:
      - local-net

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
     - "3307:3306"
    environment:
     - MYSQL_ROOT_PASSWORD=kabamysql
    networks:
      - local-net
    volumes:
      - ~/storage/docker/mysql:/var/lib/mysql

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8383:8080
#    networks:
#     - local-net

#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin:latest
#    container_name: phpmyadmin
#    restart: always
#    ports:
#     - "8081:80"
#    volumes:
#     - /sessions
#    environment:
#     - PMA_HOST=local-mysql
#    networks:
#     - local-net

networks:
    local-net:
